run:
  timeout: 5m
  tests: true
  skip-dirs:
    - scripts

linters:
  enable:
    - exhaustive
    - gosec
    - misspell
    - wastedassign
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign

issues:
  max-issues-per-linter: 0
  max-same-issues: 0