version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - exhaustive
    - gosec
    - misspell
    - wastedassign
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - gofmt
